# Generated by Django 4.1.4 on 2022-12-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=30)),
                ('order_type', models.CharField(default='BUY', max_length=4)),
            ],
        ),
    ]
