# Generated by Django 4.1.4 on 2022-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans_last_bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30, verbose_name='user_name')),
                ('stock', models.CharField(default='', max_length=30, verbose_name='stock')),
                ('shares', models.IntegerField(default=0, verbose_name='shares')),
                ('price_per_share', models.FloatField(default=0, verbose_name='price_per_share')),
                ('order_type', models.CharField(default='BUY', max_length=4, verbose_name='order_type')),
                ('sum_shares', models.IntegerField(default=0, verbose_name='sum_shares')),
                ('bet_dttm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='bet_dttm')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(default='', max_length=30, verbose_name='stock')),
                ('shares', models.IntegerField(default=0, verbose_name='shares')),
                ('price_per_share', models.FloatField(default=0, verbose_name='price_per_share')),
                ('buyer_name', models.CharField(default='', max_length=30, verbose_name='buyer_name')),
                ('seller_name', models.CharField(default='', max_length=30, verbose_name='seller_name')),
                ('trans_dttm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='trans_dttm')),
            ],
        ),
        migrations.AddField(
            model_name='bets',
            name='bet_dttm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='bet_dttm'),
        ),
        migrations.AddField(
            model_name='bets',
            name='price_per_share',
            field=models.FloatField(default=0, verbose_name='price_per_share'),
        ),
        migrations.AddField(
            model_name='bets',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='shares'),
        ),
        migrations.AlterField(
            model_name='bets',
            name='order_type',
            field=models.CharField(default='BUY', max_length=4, verbose_name='order_type'),
        ),
        migrations.AlterField(
            model_name='bets',
            name='stock',
            field=models.CharField(default='', max_length=30, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='bets',
            name='user_name',
            field=models.CharField(default='', max_length=30, verbose_name='user_name'),
        ),
    ]
