# Generated by Django 4.1.4 on 2023-01-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdjangolog',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='order_id'),
        ),
    ]
