# Generated by Django 4.1.4 on 2022-12-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_trans_last_bet_transactions_bets_bet_dttm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30, verbose_name='user_name')),
                ('stock', models.CharField(default='', max_length=30, verbose_name='stock')),
                ('shares', models.IntegerField(default=0, verbose_name='shares')),
                ('price_per_share', models.FloatField(default=0, verbose_name='price_per_share')),
                ('order_type', models.CharField(default='BUY', max_length=4, verbose_name='order_type')),
                ('order_dttm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='order_dttm')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_last_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30, verbose_name='user_name')),
                ('stock', models.CharField(default='', max_length=30, verbose_name='stock')),
                ('shares', models.IntegerField(default=0, verbose_name='shares')),
                ('price_per_share', models.FloatField(default=0, verbose_name='price_per_share')),
                ('order_type', models.CharField(default='BUY', max_length=4, verbose_name='order_type')),
                ('sum_shares', models.IntegerField(default=0, verbose_name='sum_shares')),
                ('order_dttm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='order_dttm')),
            ],
        ),
        migrations.DeleteModel(
            name='bets',
        ),
        migrations.DeleteModel(
            name='Trans_last_bet',
        ),
    ]
