# Generated by Django 4.1.4 on 2022-12-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_orders_trans_last_order_delete_bets_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='orders_db.orders',
        ),
        migrations.AlterModelTable(
            name='trans_last_order',
            table='orders_db.Trans_last_order',
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='orders_db.Transactions',
        ),
    ]
