# Generated by Django 4.1.4 on 2022-12-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_alter_orders_table_alter_trans_last_order_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trans_last_order',
            table='trans_last_order',
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
    ]
