# Generated by Django 4.1.4 on 2022-12-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0007_alter_trans_last_order_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trans_last_order',
            new_name='TransLastOrder',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=4, verbose_name='order_type'),
        ),
    ]
